services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    env_file:
      - .env
      - .env.compose
    depends_on:
      nats:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  nats:
    image: nats:2.14.2-alpine3.22@sha256:b039b46715673a9436989cfc49dde04e6bd57e205347478a58214789baf5efdc
    command: ["-c", "/etc/nats/nats.conf"]
    volumes:
      - ./config/nats/nats.conf:/etc/nats/nats.conf:ro
    ports:
      - 127.0.0.1:4222:4222
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8222/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s