services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8090:8080
    env_file:
      - .env
      - compose.env
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started
      temporal:
        condition: service_healthy

  postgres:
    image: postgres:18.4-trixie@sha256:29ee7bb30d804447dc9a91fd0d74322ae1dc3a4072cc6346f70a5ed6e783b565
    env_file:
      - .env
      - compose.env
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  nats:
    image: nats:2.14.2-alpine3.22@sha256:b039b46715673a9436989cfc49dde04e6bd57e205347478a58214789baf5efdc
    command: ["-c", "/etc/nats/nats.conf"]
    volumes:
      - ./config/nats/nats.conf:/etc/nats/nats.conf:ro
    ports:
      - 127.0.0.1:4222:4222
      - 127.0.0.1:8222:8222
      - 127.0.0.1:9222:9222

  temporal:
    image: temporalio/auto-setup:1.29.7@sha256:f14912b699cf73015ad5c4fc18d522d4b014db90e794039214dfb7c022c2644f
    env_file:
      - .env
      - compose.env
    depends_on:
      temporal-postgresql:
        condition: service_healthy
    ports:
      - 127.0.0.1:7233:7233
    volumes:
      - ./config/temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "7233"]
      interval: 5s
      timeout: 3s
      retries: 60
      start_period: 30s

  temporal-postgresql:
    image: postgres:18.4-trixie@sha256:29ee7bb30d804447dc9a91fd0d74322ae1dc3a4072cc6346f70a5ed6e783b565
    env_file:
      - .env
      - compose.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 10s

  # temporal-ui:
  #   image: temporalio/ui:2.51.0@sha256:5c72329a014fb247ef66d051dd45b3a5c251d06f82709a852e364f0fd8b69a04
  #   depends_on:
  #     temporal:
  #       condition: service_healthy
  #   environment:
  #     TEMPORAL_ADDRESS: temporal:7233
  #   ports:
  #     - 127.0.0.1:8000:8080

  # node-exporter:
  #   image: prom/node-exporter:v1.12.1@sha256:da83fae85603c4e47e6c68369a7d746e2dda683dc35ea2e234b4f171e0d92798
  #   network_mode: host
  #   command:
  #     - --path.procfs=/host/proc
  #     - --path.sysfs=/host/sys
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro

  # nats-exporter:
  #   image: natsio/prometheus-nats-exporter:0.20.1@sha256:2a4c7a0656c29dacc11dc9f3584ca08a9bc08219eaa14b332abd6234e031e5f4
  #   depends_on:
  #     nats:
  #       condition: service_started
  #   command:
  #     - -varz
  #     - -connz
  #     - -routez
  #     - -subz
  #     - http://nats:8222
  #   ports:
  #     - 127.0.0.1:7777:7777

  # postgres-exporter:
  #   image: prometheuscommunity/postgres-exporter:v0.20.1@sha256:4f3d82803c1f99ea5e767890de3557d2479ebbc711f63f2e04c663daa840057a
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     DATA_SOURCE_NAME: postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
  #   ports:
  #     - 127.0.0.1:9187:9187
