loop:
  server:
    bind_addr: 0.0.0.0:8080
    base_path: /
    timeout: 10s
    shutdown_timeout: 30s
  logger:
    format: text
    level: info
  telegram:
    api_key: ${TELEGRAM_API_KEY}
    channel_id: ${TELEGRAM_CHANNEL_ID}
  tavily:
    api_key: ${TAVILY_API_KEY}
  dirs:
    git: .git
    tasks: .tasks
    worktrees: .worktrees
    sessions: .sessions
    providers: providers
    agents: agents
  providers:
    opencode-go:
      api_key: ${PROVIDER_API_KEY_OPENCODE}
      base_url: https://opencode.ai/go/v1
      models_list_url: https://opencode.ai/go/v1/models
    opencode-zen:
      api_key: ${PROVIDER_API_KEY_OPENCODE}
      base_url: https://opencode.ai/zen/go/v1
      models_list_url: https://opencode.ai/zen/go/v1/models
